<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LQ6L55O" failures="1" tests="12" name="Testcases.New_User_Creation" time="11.659" errors="0" timestamp="2024-09-13T18:01:59 IST" skipped="0">
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_MENU_IS_CLICKED_SUCCESSFULLY" time="0.202"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_IS_NAVIGATED_INTO_ADD_USER_SECTION_WHEN_CLICK_ON_ADD_USER_BUTTON" time="0.290"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_ENTER_THE_USERNAME_IN_USERNAME_FIELD" time="0.600"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_ABLE_TO_ENTER_MAILID_SUCCESSFULLY" time="0.508"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_ABLE_TO_SELECT_THE_INDIA_Dial_CODE" time="0.788"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_IS_ABLE_TO_ENTER_THE_10_DIGIT_MOBILE_NUMBER_ON_MOBILE_NUMBER_FIELD" time="0.346"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_IS_ABLE_TO_SELECT_THE_ACCESS_ROLE" time="1.553"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_IS_ABLE_TO_SELECT_THE_LOCATION_LEVEL_AS_COUNTRY_IN_LEVEL_DROPDOWN" time="1.453"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_USER_IS_ABLE_TO_SELECT_THE_LOCATION_IN_LOCATION_FIELD" time="2.500"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_DEFAULT_PASSWORD_DISPLAYED_AS_ENCRYPED_FORMAT_IN_PASSWORD_FIELD" time="1.375"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_CONFIRM_PASSWORD_IS_FILLED_WITH_DEFAULT_PASSWORD" time="1.377"/>
  <system-out/>
  <testcase classname="Testcases.New_User_Creation" name="VERIFY_THAT_NEW_USER_IS_CREATED_SUCCESSFULLY_BY_CLICKING_THE_SUBMIT_BUTTON" time="0.667">
    <failure message="Popup message does not contain the expected text. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Popup message does not contain the expected text. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Testcases.New_User_Creation.VERIFY_THAT_NEW_USER_IS_CREATED_SUCCESSFULLY_BY_CLICKING_THE_SUBMIT_BUTTON(New_User_Creation.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- VERIFY_THAT_NEW_USER_IS_CREATED_SUCCESSFULLY_BY_CLICKING_THE_SUBMIT_BUTTON -->
  <system-out/>
</testsuite> <!-- Testcases.New_User_Creation -->
